config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :horses, shallow: true do
    resources :bookings, only: [:create, :update, :show, :delete] do
      member do
        patch "accepted", to:'bookings#set_status_accepted'
        patch "decline", to:'bookings#set_status_decline'
        patch "done", to:'bookings#set_status_done'
        patch "pending", to:'bookings#set_status_canceled'
      end
    end
  end

  resources :users, only: [:show]
  get 'team', to: "pages#team"
  get 'about', to: "pages#about"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :horse
  belongs_to :user
  validates :horse_id, presence: true
  validates :user_id, presence: true
  validates_date :start_date, after: -> { Date.today }, on: :create
  validates_date :end_date, after: -> { :start_date }, on: :create

  def mark(status)
    self.status = status
    save!
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: %i[show set_status_pending set_status_accepted set_status_decline set_status_done]
  before_action :booking_update

  def show
    if current_user == @booking.user || current_user == @booking.horse.user
      @horse = @booking.horse
    else
      redirect_to horses_path
    end
  end

  def create
    @horse = Horse.find(params[:horse_id])
    @booking = current_user.bookings.new(booking_params)
    @booking.horse = @horse
    @booking.price = booking_price
    @booking.status = 'En attente'

    if @horse.user == current_user
      flash[:alert] = 'Vous ne pouvez pas réserver votre propre cheval.'
      render 'horses/show'
      return 0
    elsif @booking.save
      respond_to do |format|
        format.html {
          redirect_to @booking
          flash[:notice] = 'La demande de demi-pension a bien été envoyée au propriétaire.'
        }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'horses/show' }
        format.js
      end
    end
  end

  def update
    @booking = Booking.find(params[:id])
    @horse = @booking.horse

    if @booking.update(booking_params)
      redirect_to @booking
      flash[:notice] = 'La mise-à-jour des informations a bien été prise en compte.'
    else
      render :show
    end
  end

  def set_status_accepted
    @booking.mark('Valider')
    redirect_to @booking
  end

  def set_status_decline
    @booking.mark('Refuser')
    redirect_to @booking
  end

  def set_status_done
    @booking.mark('Terminer')
    redirect_to @booking
  end

  def set_status_canceled
    @booking.mark('Annuler')
    redirect_to @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :horse_id, :user_id, :price, :rating, :status)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_update
    Booking.all.each do |booking|
      booking.mark('Terminer') if booking.end_date == Date.today
    end
  end

  def booking_price
    month_num = (@booking.end_date - @booking.start_date) / 30
    @horse.monthly_price * month_num.to_f.round(2)
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for([horse, booking], remote: true) do |f| %>
  <p id="top-price">Prix par mois : <span id= "horse_price"><%=  @horse.monthly_price  %></span> €</p>
  <%= f.input :start_date, label: "Date de début", as: :date, start_year: Date.today.year,
                                                   start_day: Date.today + 1,
                                                   end_year: Date.today.year + 5,
                                                   order: [:day, :month, :year] %>


  <%= f.input :end_date, label: "Date de fin", as: :date, start_year: Date.today.year,
                                               end_year: Date.today.year + 5,
                                               order: [:day, :month, :year]  %>


  <p><strong>Nombre de mois :</strong> <span id="days"></span></p>
  <p><strong>Prix total : </strong><span id="price"></span> €</p>
  <%= f.submit class: 'btn btn-primary', value: "Réserver" %>
<% end %>

app/views/bookings/create.js.erb
<% if @booking.errors.any? %>
  $('#new_booking').html("<%= j render 'bookings/form', horse: @horse, booking: @booking %>");
<% else %>
  window.location.replace("<%= booking_path(@booking) %>");
<% end %>

app/views/bookings/show.html.erb
<h1 id="booking-show">Le demi-pension</h1>

<div class="container">
  <div class="row">
    <div class="booking-show">
      <div class="col-xs-12 col-sm-3">
        <h4>Le propriétaire :</h4>
        <% if @horse.user.facebook_picture_url == nil %>
        <%= cl_image_tag @horse.user.photo.path, id: "user_pic", class: "avatar-extralarge"  %>
        <% else %>
        <%= image_tag @horse.user.facebook_picture_url, id: "user_pic", class: "avatar-extralarge" %>
        <% end %>
        <%= @horse.user.first_name %>
      </div>

      <div class="col-xs-12 col-sm-3">
        <h4>Le demi-pensionnaire :</h4>
        <% if @booking.user.facebook_picture_url == nil %>
        <%= cl_image_tag @booking.user.photo.path, id: "user_pic", class: "avatar-extralarge"  %>
        <% else %>
        <%= image_tag @booking.user.facebook_picture_url, id: "user_pic", class: "avatar-extralarge" %>
        <% end %>
        <%= @booking.user.first_name %>
      </div>

      <div class="col-xs-12 col-sm-3">
        <div class="booking-informations text-center">
          <h4>Informations</h4>
          <p>Date de début : <%= @booking.start_date %></p>
          <p>Date de fin : <%= @booking.end_date %></p>
          <p>Prix total : <%= @booking.price %> €</p>
        </div>
      </div>

      <div class="col-xs-12 col-sm-3">
        <div class="message-status">
          <% if @booking.status == "En attente" && current_user == @booking.horse.user %>
            <p class="status pending">Statut : <%= @booking.status %></p>
              <div class="col-xs-12">
                <%= link_to 'Accepter', accepted_booking_path(@booking), class: "btn btn-success btn-margin", method: :patch%>
              </div>
              <div class="col-xs-12">
               <%= link_to 'Refuser', decline_booking_path(@booking), class: "btn btn-danger btn-margin btn-size", method: :patch%>
              </div>
              <div class="col-xs-12">
                <%= link_to 'Annuler', decline_booking_path(@booking), class: "btn btn-warning btn-margin btn-size", method: :patch%>
              </div>
          <% elsif @booking.status == "En attente" && current_user == @booking.user %>
            <p class="status pending">Statut : <%= @booking.status %></p>
            <p><%= link_to 'Annuler', decline_booking_path(@booking), class: "btn btn-warning btn-margin btn-size", method: :patch%></p>
          <% elsif @booking.status == "Valider" %>
            <p class="status.accepted">Statut : <%= @booking.status %></p>
            <%= link_to 'Annuler', decline_booking_path(@booking), class: "btn btn-warning", method: :patch%>
          <% elsif @booking.status == "Refuser" %>
            <p class="status.declined">Statut : <%= @booking.status %></p>
          <% elsif @booking.status == "Annuler" %>
            <p class="status.declined">Statut : <%= @booking.status %></p>
          <% else @booking.status == "Terminer" %>
            <p class="status.accepted">Statut : <%= @booking.status %></p>
        </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

<div class="white-wrapper">
  <div class="horse-description">
    <div class="container">
      <h3>Infos sur le cheval</h3>
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <p><strong>Nom :</strong> <%= @horse.name %></p>
          <p><strong>Âge :</strong> <%= (Date.today - @horse.birth_date).to_i / 365 %> ans</p>
          <p><strong>Sexe :</strong> <%= @horse.sexe %></p>
          <p><strong>Race :</strong> <%= @horse.race %></p>
        </div>
        <div class="col-xs-12 col-sm-4">
          <p><strong>Discipline :</strong> <%= @horse.disciplines %></p>
          <p><strong>Caractère :</strong> <%= @horse.character %></p>
          <p><strong>Niveau requis :</strong> Galop <%= @horse.required_level %></p>
          <p><strong>Prix de la demi-pension :</strong> <%= @horse.monthly_price %> € / mois</p>
        </div>
      <div class="col-xs-12 col-sm-4">
        <p><strong>Description :</strong> <%= @horse.description %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <% if @booking.rating.nil? %>
          <%= simple_form_for @booking do |f| %>
            <%= f.input :rating, collection: 1..5, label: "Donnez une note au cheval :" %>
            <%= f.button :submit, value: "Valider", class:"btn btn-primary"%>
          <% end %>
        <% else %>
          <p>Note de la demi-pension : <%= @booking.rating %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

<h3 id="map-title">Localisation</h3>
<div id="map" style="width: 100%; height: 300px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
    {
    "lat": <%= @booking.horse.latitude %>,
    "lng": <%= @booking.horse.longitude %>,
  }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });
  <% end %>
<% end %>