config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :horses, shallow: true do
    resources :bookings, only: [:create, :update, :show, :delete] do
      member do
        patch "accepted", to:'bookings#set_status_accepted'
        patch "decline", to:'bookings#set_status_decline'
        patch "done", to:'bookings#set_status_done'
        patch "pending", to:'bookings#set_status_canceled'
      end
    end
  end

  resources :users, only: [:show]
  get 'team', to: "pages#team"
  get 'about', to: "pages#about"
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/ophelied3/rails-airbnb-clone"><i class="fa fa-github"></i></a>
    <%= link_to "Team", team_path %>
  </div>
  <div class="footer-copyright">
    For the people who <i class="fa fa-heart"></i> horses.
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed-top">
  <div class="navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">



      <% if user_signed_in? %>

        <!-- Links when logged in -->


        <%= link_to "Rechercher un cheval", horses_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Ajouter une annonce", new_horse_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= safe_image_tag(current_user) %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to(current_user) do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item btn btn-danger btn-sm" %>
      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Rechercher un cheval", horses_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to "Ajouter une annonce", new_horse_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>